### ISSUE TITLE
Invalid class `dgCMatrix` object

### ISSUE THREAD

**Issue by ajauhri** [HenrikBengtsson/R.matlab#2] opened 2014-11-28 02:44 UTC
Trying to load a MAT file with objects of two classes - double & cell. 
![readmat](https://cloud.githubusercontent.com/assets/399844/5223092/bc47293a-7664-11e4-917b-5a3b4c257d65.png)

The variables shown in the image belong to the following classes:
* `X`, `Y`, `Y2`  - double (sparse matrices) 
* `all_sentiments` - double (vector) 
* `all_genres` - cell

**Comment by ajauhri** [comment] 2015-01-20 20:44
It is preferred to use `Matrix` package as opposed to `SparseM`. Although on `data <- readMat("sparse_matrix.mat", sparseMatrixClass='Matrix')`, I see the following error:
` Error in validObject(.Object) : 
  invalid class “dgCMatrix” object: lengths of slots 'i' and 'x' must match`

**Comment by HenrikBengtsson** [comment] 2015-01-20 21:04
Thanks for the report.

Could you please provide:
1. sessionInfo() after you receive the error.
2. traceback() after you receive the error.
3. A *minimal* MAT file so that I can try to reproduce this. I'll have to
debug and step through the parsing of this file manually so it's extremely
helpful if it is very small and the problematic sparse matrix is early on
in the MAT file (ideally the only object).

**Comment by HenrikBengtsson** [comment] 2015-01-20 21:05
(please send that info as plain text - not screenshots)

**Comment by ajauhri** [comment] 2015-01-21 00:01
> data<-readMat('test_R_matlab.mat', sparseMatrixClass='Matrix')
Error in validObject(.Object) :
  invalid class “dgCMatrix” object: lengths of slots 'i' and 'x' must match
> sessionInfo()
R version 3.0.2 (2013-09-25)
Platform: x86_64-pc-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
LC_ADDRESS=C               LC_TELEPHONE=C
LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] Matrix_1.1-4   R.matlab_3.1.1

loaded via a namespace (and not attached):
[1] grid_3.0.2        lattice_0.20-29   R.methodsS3_1.6.1 R.oo_1.18.0
R.utils_1.34.0    tools_3.0.2
> traceback()
10: stop(msg, ": ", errors, domain = NA)
9: validObject(.Object)
8: initialize(value, ...)
7: initialize(value, ...)
6: new(className, x = pr, p = as.integer(jc), i = as.integer(ir -
       1L), Dim = as.integer(c(nrow, ncol)))
5: mat5ReadMiMATRIX(this, tag)
4: readMat5DataElement(this)
3: readMat5(con, firstFourBytes = firstFourBytes, maxLength = maxLength)
2: readMat.default("test_R_matlab.mat", sparseMatrixClass = "Matrix")
1: readMat("test_R_matlab.mat", sparseMatrixClass = "Matrix")

Let me know if you require anything else.
Thanks!


- Abhinav

**Comment by ajauhri** [comment] 2015-01-21 00:05
Here is the link to the MAT file - https://dl.dropboxusercontent.com/u/10119973/test_R_matlab.mat

**Comment by HenrikBengtsson** [comment] 2015-01-21 18:48
Thank you for this.  I can now reproduce the error:

```r
> readMat("test_R_matlab.mat")
Error in validObject(.Object) :
  invalid class "dgCMatrix" object: lengths of slots 'i' and 'x' must match
> traceback()
10: stop(msg, ": ", errors, domain = NA)
9: validObject(.Object)
8: initialize(value, ...)
7: initialize(value, ...)
6: new(className, x = pr, p = as.integer(jc), i = as.integer(ir -
       1L), Dim = as.integer(c(nrow, ncol)))
5: mat5ReadMiMATRIX(this, tag)
4: readMat5DataElement(this)
3: readMat5(con, firstFourBytes = firstFourBytes, maxLength = maxLength)
2: readMat.default("test_R_matlab.mat")
1: readMat("test_R_matlab.mat")
```

I'll look into this.

In meanwhile, would mind donating this MAT file to the package such that I can add it to R.matlab's unit and redundancy tests?

**Comment by ajauhri** [comment] 2015-01-21 19:09
Don't mind that. Have created a PR for the same.

On Wed, Jan 21, 2015 at 10:48 AM, Henrik Bengtsson <notifications@github.com

**Comment by HenrikBengtsson** [comment] 2015-01-21 20:30
This seems to be due to that sparse matrix `X` contains all zeros, which was a corner case.  I've committed a patch to  'develop' [readMat.R](https://github.com/HenrikBengtsson/R.matlab/blob/develop/R/readMat.R). 

You should be able install it with:
```r
source("http://callr.org/install#HenrikBengtsson/R.matlab@develop")
```

However, when adding package [tests](https://github.com/HenrikBengtsson/R.matlab/blob/develop/tests/readMat.R#L83-L105) for this case, I discovered additional issues, which (for you) are hopefully due to bugs with `sparseMatrixClass='SparseM'` and `sparseMatrixClass='matrix'`.   Because of these, I've commented out some assertions in that part of the tests.  Please make sure you get the values you expect with `sparseMatrixClass='Matrix')` for all elements of that test file.

(That's all I have time for now)

**Comment by ajauhri** [comment] 2015-01-22 02:49
Thanks for your prompt response! The patch works fine with my original MAT file now. Although, the minimal version of MAT file with all zero-entries was sent by chance, so I guess your submitted patch is working with the original MAT file probably because of commenting of assertions.

**Closed** 2015-02-01 00:32 UTC
Labels: bug
